package eugenzh.ru.pravradioapp.Common;

public enum RequestResult {
    REQUEST_RESUTL_SUCC,
    REQUEST_RESULT_FAIL_SERVER_NOT_RESPONSE,
    REQUEST_RESULT_FAIL_STORAGE_INACCESSIBLE,
    REQUEST_RESULT_FAIL_RESOURSE_NOT_CREATED,
    REQUEST_RESULT_FAIL_NETWORK
}
